name = "flappy-snake-api"
main = "index.ts"
compatibility_date = "2024-01-01"

# Update this with your actual D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "flappy-snake-leaderboard"
database_id = "c05e3ac7-2a32-496c-8ee4-e75531b97845"
